apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: orchestrationapi-notifications-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-api-configmap
            - secretRef:
                name: notifications-api-secret