apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secret
type: Opaque
data:
  RabbitMQ__Password: YWRtaW4=
  ConnectionStrings__MS_NotificationsAPI: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlLDE0MzM7RGF0YWJhc2U9TVNfTm90aWZpY2F0aW9uc0FQSTtVc2VyIElkPXNhO1Bhc3N3b3JkPVNlbmhhQDEyMztUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU=
  Serilog__WriteTo__0__Args__databaseUrl: bW9uZ29kYjovL3Jvb3Q6cm9vdEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvbG9nc19kZXY/YXV0aFNvdXJjZT1hZG1pbg==